# These are supported funding model platforms

github:             # github: USERNAME or github: [USERNAME, USERNAME, USERNAME, USERNAME]
ko_fi:              # ko_fi: USERNAME
patreon:            # patreon: USERNAME
buy_me_a_coffee:    # buy_me_a_coffee: USERNAME
custom:             # custom: LINK1 or custom: [LINK1, LINK2, LINK3, LINK4]
